### ISSUE TITLE
Offer to run the command to reset the yubikey to the history issue

### ISSUE THREAD

**Issue by mscherer** [mcepl/gen-oath-safe#3]
Since the user has to copy the command line to execute it on a yubikey, what about detecting if a yubikey is plugged currently ( one and only one ) and run the command instead of of asking to the user to do it ? This way, this prevent the issue of having the command with the seed in history, since the recommendation of using history -c can be a bit annoying.

( of course, we would need to ask the slot, and this could maybe also serve for #2 to detect if we can set the numeric-keypad option )

**Comment by mcepl** [comment]
@72Zn Should we close this? This is strictly speaking not fixed by #13, but it shouldn’t matter anymore, should it?

**Comment by 72Zn** [comment]
@mcepl yes, I'd argue this can be closed. With #13 the script can now detect if a Yubikey is inserted and then probes for an empty slot, or asks the user which slot should be used (in case both slots are already configured). It then tries to write the configuration to the Yubikey. This way, the command will not appear in the bash history. Of course, the key must be inserted before running the command. If the key is not inserted, the behavior is just like before. We could ask the user to insert a key, but I'd actually prefer to keep user interaction to a minimum. Both the usage as well as the man page state that the Yubikey has to be inserted before running the script in order to write the configuration to the key. Imho this should be enough.
